# Generated by Django 4.2.3 on 2023-09-29 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('feedback', '0004_remove_feedback_post_alter_feedback_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='post',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel'),
        ),
    ]
