# Generated by Django 4.2.3 on 2023-09-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedback_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='post',
        ),
    ]
