# Generated by Django 4.2.3 on 2023-10-03 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('feedback', '0006_remove_feedback_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='blog_name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel'),
        ),
    ]
