# Generated by Django 4.2.3 on 2023-10-03 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('feedback', '0007_feedback_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='blog_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel'),
        ),
    ]
