# Generated by Django 4.2.3 on 2023-10-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_feedbackmodel_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='blog_name',
        ),
    ]
