# Generated by Django 4.2.3 on 2023-10-04 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('feedback', '0012_feedback_delete_feedbackmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='blog_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel'),
            preserve_default=False,
        ),
    ]
