# Generated by Django 4.2.3 on 2023-10-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_feedback_blog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='blog_name',
        ),
    ]
