# Generated by Django 4.2.3 on 2023-09-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='mobile_no',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='choice',
            new_name='role',
        ),
    ]
