# Generated by Django 4.2.3 on 2023-10-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_paymentgatewaysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
