# Generated by Django 4.2.3 on 2023-10-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_paymentgatewaysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='amount',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
