# Generated by Django 4.2.3 on 2023-10-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_userinformation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
